# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: srvr.in
email: srih4ri@gmail.com
tagline: > # this means to ignore newlines until "baseurl:"
  Blog posts and notes about software development, philosophy
  and what not!
description: > # this means to ignore newlines until "baseurl:"
  A personal blog with notes and learnings from software    engineering and product development. Also musings about other hobbies like electronics and gardnening.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://srvr.in" # the base hostname & protocol for your site
author:
  twitter: srih4ri
twitter:
  card: summary
  username: srih4ri
social:
  name: Srihari K
  links:
    - https://twitter.com/srih4ri
    - https://github.com/srih4ri
    - https://www.linkedin.com/in/srih4ri/
twitter_username: srih4ri
github_username:  srih4ri
collections:
  notes:
    output: true
# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
